apiVersion: batch/v1
kind: Job
metadata:
  name: recommending-model-e5737d9
  namespace: jorgesilva
spec:
  template:
    spec:
      containers:
        - name: recommending-model-e5737d9
          image: silvajorge/recommending-model:e5737d9
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /mnt/data
              name: data-volume
          env:
            - name: INPUT_FILE_LINK
              value: https://raw.githubusercontent.com/jorgesilva2407/recommending-system/main/data/playlists.csv
            - name: OUTPUT_FILENAME
              value: /mnt/data/model.pkl
            - name: MIN_SUPPORT
              value: "0.1"
            - name: MIN_CONFIDENCE
              value: "0.5"
      restartPolicy: Never
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: project2-pvc-jorgesilva
